### ISSUE TITLE
Would you like to add this to the cryogen-project org?

### ISSUE THREAD

**Issue by lacarmen** [sanel/blogger2cryogen#1]
Hey, would you be interested in contributing this lib to the [Cryogen Org](https://github.com/cryogen-project)? 

I think it would be a useful tool to have under the Cryogen "umbrella" and I would add you to the org as a collaborator :)

**Comment by sanel** [comment]
Hi,

Sure! I'll be happy to do that. What should I do? Also, it depends on [cryogen-html](https://github.com/sanel/cryogen-html) so would you like me to contribute that library as well?

Best.

**Comment by lacarmen** [comment]
That would be great! I've invited you to the Collaborators team in the organization :)

It's kind of weird but you'll have to transfer ownership of the repos to me first and then I have to transfer them to the org because I have admin access.

**Comment by sanel** [comment]
No problem; let me try that...

**Comment by lacarmen** [comment]
Awesome, I've moved both of them to cryogen-project. You should have read/write access :)
